title: Arabella Abad
url: "https://arabellaabad.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Portfolio"
   link: "portfolio"
 - name: "Contact"
   link: "contact"
 - name: "CV"
   link: "resume.pdf"
